### PR TITLE
Add support for CannotConnect message

### LINKED ISSUE #451: Implement CannotConnect message
Capture the username and raise an event.  I'm not sure how this would be useful, but it would be nice to track.

### PR DESCRIPTION
**Pull request by jpdillingham**
Closes #451

### CODE REVIEW

**Comment by mathiascode** [comment]
Be careful when sending this message. We had a lot of failing transfers in Nicotine+ due to firewalled users + indirect connection attempts arriving before direct connections were attempted to us. Sending this message seems to cancel all connection attempts on the remote end.

**Comment by jpdillingham** [comment]
@mathiascode thanks for the heads up!  Reminds me of similar timing issues I've had with `UploadFailed`.

Are you just not sending this message, or did you add a delay?

**Comment by mathiascode** [comment]
I decided to stop sending the message. I barely receive such messages from other users, mostly ending up falling back to a timeout anyway, so my guess is that the official client doesn't send it either anymore.

**Comment by mathiascode** [comment]
I wonder how recent the behavior of attempting direct and indirect connections simultaneously is, since the previous Nicotine+ documentation/code always treated indirect connections as a fallback once direct ones failed.

**Comment by jpdillingham** [comment]
It definitely seems like it was a recent addition.  I've seen indirect connections come in substantially before direct attempts, so I think I'll follow your lead and choose not to send this message after a failed indirect attempt.

Incoming `CannotConnect` messages seem pretty rare so I think you might be correct that it is deprecated.  There's a surprisingly large number of NS users still around.

**Pull request merged**
