### PR TITLE
General project structure overhaul

### PR DESCRIPTION
**Pull request by MeikTranel**
Key takeaways:

- Extracted build infrastructure only logic into a locally executable/debuggable cake build script
- Added a Windows build to put test against Full Frameworks implementing .NET Standard 2.0 (test TFMs are automatically resolved based on current OS to ease development on linux and similar platforms)
- Cleaned up static code analysis configs
- Used the already existing domain based project structure to introduce rules and configs based on domain (tests = IsTestable, PackageReference for Microsoft.NET.Test.Sdk, Option for XUnit and TestCoverage...)
- Added some VSCode workspace recommendations, launch and task configs

### CODE REVIEW

**Comment by jpdillingham** [comment]
This is impressive, thanks so much!

**Comment by MeikTranel** [comment]
Hehe t'was a pleasure. By the way ive forgotten to ask this: You use the free open source plan from Azure DevOps right?
I have designed this so you can write those last steps for publishing with a Release Pipeline, that way you can put that nuget push job behind a manual gate where you push the release button and do the final config there. Azure DevOps is moving to put release configs under Config as Code,too. But until then manual release don't sound very wrong to me.

**Comment by jpdillingham** [comment]
I'll have to look into releases, my experience with Azure DevOps is limited to maybe 30 minutes :)

Speaking of, I can't seem to find the code coverage report.  This isn't a huge deal since I was planning to integrate with codecov.io at some point, just curious.

I'm also wondering if it is possible to put all of the various build configs and pipeline yaml in the build folder, and whether the tools folder could be moved under that as well, just to reduce clutter in the root.  I'm guessing conventions require some of it, but I thought I recalled that Azure allowed you to put the yaml in a subdirectory so it's been in the back of my mind.

Lastly, I can't get the project to build locally as I'm missing a 4.7.x targeting pack; it looks like the two test projects are targeting framework as well as core.  Was this intentional?

**Comment by MeikTranel** [comment]
I'm not sure. Azure definitely lets you include files from other folders. But seeing how little lines we have in there you wouldn't really gain anything from moving only some of it to another folder (i don't think you can put the main azure-pipelines.yml somewhere else... i might be wrong).

As for the cake stuff it's kind of a fixed in place... that's one of the little irks of Cake. If you look at gitignore.io's CSharp preset under https://www.gitignore.io/api/csharp you'll see that it basically has been like this for so long that its like an accepted standard now. There's nothing technically holding you back from moving the folders down the tree... but you'll see that the cake script will becomes insanely complex and weird, because you need to think about every path as if they are one directory up and then down again constantly having to think around the working directory which at some point (especially for build script where 90% of business logic is basically file / folder manipulation) becomes absurdly annoying... also omnisharp (the official c# extension) doesn't work with those configs... at which you kinda lost the benefits of having a debuggable c# build script.

Regarding the targeting pack, yes... kind of... have a look at this:

https://github.com/jpdillingham/Soulseek.NET/blob/905f362ced2df0ecd9c987e597c3ace1a5e0f29d/tests/Directory.Build.props#L2-L10

I made it so that Windows-only target frameworks are added to the TargetFrameworks when building the tests on a windows development machine. I choose these two frameworks for two reasons:

- They are extremely popular TFMs in the .NET Framework world right now. 
- Besides 4.8 which is kinda out kinda not,  4.6 & and 4.7 are the only full frameworks that implement .NET Standard...

but why two then you ask? Because while 4.6.2 was initially marked as .NET Standard 2.0 compliant when they first publicized the standard even though 4.6.2 was long released, they did so without noticing that some types were missing down the line. The result is that some time late summer this year @terrajobst had to basically revoke .NET Standard 2.0 compliance of 4.6.2... but thousands of libraries etc. were already built under this assumptions, which means that you can use .NET Standard 2.0 libraries from 4.6.2, but there are some _very rare cases_ (another one of the people who asked me help actually didn't notice this because he only ever tested .NET Core... was the first time i hit this exact problem, see: https://github.com/MeikTranel/MigrationSupport/issues/1#issuecomment-442956717) where this can lead to Type missing exceptions at runtime.
So at the current point in time it is smart to always test against net462 **and** add some more recent full framework versions, too. You can use 4.7.2 or 4.8 no immediate difference from my perspective, but there are cases where you WILL find .NET Standard related bugs that will not show up in versions higher than 4.6.2.

**Comment by MeikTranel** [comment]
I opened issue #17 to track the coverage report missing and mark the issue https://github.com/MeikTranel/MigrationSupport/issues/3 as resolved as this is only minor ( the coverage overview is still picked up by Azure DevOps. Only the ReportGenerator browser is missing ).

**Comment by jpdillingham** [comment]
Thanks for following up, everything is making more sense now that I've had a chance to review some of the config.  I installed the targeting pack and builds are working.

**Comment by jpdillingham** [comment]
@MeikTranel I managed to get the code coverage uploaded to codecov, could you take a look at the build script and pipeline yaml and let me know if I've done it "right"?

**Comment by MeikTranel** [comment]
I mean you could have used this: https://github.com/cake-contrib/Cake.Codecov

But in the end all that matters is that it works.

**Pull request merged**
